version: "3.9"

# ================== SERVICES INTERNES ==================
services:
  web:
    container_name: ERP_interne
    build:
      context: "./Services_interne/ERP"
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./Services_interne/ERP/www:/var/www/html

    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.4 
    dns : 
      - 172.16.0.2

  db:
    container_name: DB_interne
    build:
      context: "./Services_interne/BDD"
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Services_interne/BDD/woodytoys_db/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.9
    dns :
      - 172.16.0.2

  resolver:
    container_name: Resolver_interne
    build:
      context: "./Services_interne/Resolveur"
      dockerfile: Dockerfile
        
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.2
    dns :
      - 172.16.0.2
  soa:
    container_name: soa_interne
    build:
      context: "./Services_interne/SOA-interne"
      dockerfile: Dockerfile
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.11
    dns : 
      - 172.16.0.2

  testpc:
    container_name: PC_interne
    build:
      context: "./Services_interne/PCtest"
      dockerfile: Dockerfile
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.10 
    dns : 
      -  172.16.0.2
    

  mail:
    container_name: Mail_interne
    build:
      context: "./Services_interne/Mail"
      dockerfile: Dockerfile
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.3
    dns: 
      - 172.16.0.2

# ================== SERVICES PUBLIQUES ==================
  soa_pub:
    container_name: soa_publique
    build: 
      context: "./Services_Publiques/SOA-publique"
      dockerfile: Dockerfile
    networks:
      DMZ:
        ipv4_address : 172.16.1.3
    dns:
      - 172.16.1.2

  web_pub:
    container_name: ERP_publique
    build:
      context: "./Services_Publiques/web"
      dockerfile: Dockerfile
    volumes:
      - ./Services_Publiques/ERP/www:/var/www/html
    ports:
      - "8080:80"
    networks:
      DMZ:
        ipv4_address : 172.16.1.4
    dns:
      - 172.16.1.2
      
# ================== NETWORK ==================
networks:
  ZoneInterne:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  DMZ :
    driver : bridge
    ipam : 
      driver : default
      config : 
        - subnet : 172.16.1.0/24
