version: "3"

services:
  web:
    depends_on:
      - db
    container_name: WEB

    
    build: ./ERP
    ports:
      - "8080:80"
    
    volumes:
      - ./web:/var/www/html

  db:
    build: ./DB
    container_name: DB
    restart : always
    ports:
      - "3036:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME : admin
      MYSQL_PASSWORD : admin
    
    volumes:
      - ./mysql:/var/lib/mysql

  resolver:
    build: ./Resolveur
    container_name: Resolveur
    ports:
      - "53:53"
    
    volumes:
      - ./bind:/etc/bind

  soa:
    build: ./SOA-interne
    container_name: SOAs
    volumes:
      - ./soa:/etc/bind

  testpc:
    build: ./PCtest
    container_name: TESTpc

  mail:
    build: ./Mail
    container_name: Mail
    ports:
      - "25:25"
      - "110:110"
      - "993:993"
        
      
