version: "3.9"

services:
  web:
    container_name: ERP
    build:
      context: ./ERP
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./ERP/www:/var/www/html

  db:
    container_name: DB
    build:
      context: ./BDD
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  resolver:
    container_name: Resolver
    build:
      context: ./Resolveur
      dockerfile: Dockerfile
   
  soa:
    container_name: SOA_interne
    build:
      context: ./SOA-interne
      dockerfile: Dockerfile
    

  testpc:
    container_name: TESTpc
    build:
      context: ./PCtest
      dockerfile: Dockerfile
    

  mail:
    container_name: Mail_interne
    build:
      context: ./Mail
      dockerfile: Dockerfile
   
        
      
