version: "3.9"

services:
  web:
    container_name: ERP
    build:
      context: ./ERP
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./ERP/www:/var/www/html

    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.4 

  db:
    container_name: DB
    build:
      context: ./BDD
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  resolver:
    container_name: Resolver
    build:
      context: ./Resolveur
      dockerfile: Dockerfile
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.2
   
  soa:
    container_name: SOA_interne
    build:
      context: ./SOA-interne
      dockerfile: Dockerfile
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.11
    

  testpc:
    container_name: TESTpc
    build:
      context: ./PCtest
      dockerfile: Dockerfile
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.10 
    

  mail:
    container_name: Mail
    build:
      context: ./Mail
      dockerfile: Dockerfile
    networks :
        ZoneInterne : 
            ipv4_address : 172.16.0.3


# ================== NETWORK ==================
networks:
  ZoneInterne:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

# networks : 
#   LAN :
#     driver : bridge
#     ipam : 
#       driver : default
#       config : 
#         - subnet : 192.168.0.0/24

# networks : 
#   DMZ :
#     driver : bridge
#     ipam : 
#       driver : default
#       config : 
#         - subnet : 172.16.1.0/24