version: "3"

services:
  web:
    build: ./Web
    
    volumes:
      - ./web:/var/www/html

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME : admin
      MYSQL_PASSWORD : admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  resolver:
    build: ./Resolveur
    
    volumes:
      - ./bind:/etc/bind

  soa:
    build: ./SOA-interne
  
   
    volumes:
      - ./soa:/etc/bind

  testpc:
    build: ./Pctest
        
      
